# Generated by Django 4.1.5 on 2023-01-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='details',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
        migrations.CreateModel(
            name='NoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_to_complete', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=255)),
                ('attachments', models.ImageField(blank=True, upload_to='')),
                ('details', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.notes')),
            ],
        ),
    ]
